export const resources = {
  bracket_battle_prefix: 'BATTLE #',
  bracket_feed_label: 'ON-AIR',
  bracket_feed_title: 'LIVE FEED',
  bracket_participants_prefix: 'PARTICIPANTS:',
  bracket_placeholder: 'Bracket will appear after qualification ends.',
  bracket_power_title: 'POWER RANKINGS',
  bracket_round_final: 'FINAL',
  bracket_round_semifinal: 'SEMIFINALS',
  bracket_round_top8: 'QUARTERFINALS',
  bracket_status_live: 'LIVE',
  bracket_status_pending: 'PENDING',
  bracket_status_winner: 'WINNER',
  bracket_title: 'PRO BRACKET',
  content_not_found: "Content not found",
  dashboard_action_generate_top8: 'GENERATE TOP 8',
  dashboard_action_participants: 'MANAGE PARTICIPANTS',
  dashboard_action_show_qr: 'SHOW CONNECTION QR',
  dashboard_action_start_battles: 'START BATTLES',
  dashboard_action_start_qualification: 'START QUALIFICATION',
  dashboard_event_live: 'EVENT LIVE · HOST DASHBOARD',
  dashboard_hero_status: 'SYSTEM STANDBY',
  dashboard_hero_title: 'READY TO CLASH',
  dashboard_judge_hint: 'Use the JUDGING tab to score and vote.',
  dashboard_reset_role: 'RESET ROLE',
  create_event_title: 'NEW EVENT',
  create_event_name_label: 'EVENT NAME',
  create_event_category_label: 'CATEGORY / STYLE',
  create_event_format_label: 'BATTLE FORMAT',
  create_event_judges_label: 'NUMBER OF JUDGES',
  create_event_submit: 'CREATE EVENT',
  dashboard_logs_title: 'SYSTEM LOGS',
  dashboard_mc_placeholder: 'MC view coming soon.',
  dashboard_server_health: 'HEALTH',
  dashboard_server_health_value: 'STABLE',
  dashboard_server_ip: 'IP ADDRESS',
  dashboard_server_offline: 'OFFLINE',
  dashboard_server_online: 'ONLINE',
  dashboard_server_port: 'PORT',
  dashboard_server_title: 'SERVER STATUS',
  dashboard_server_uptime: 'UPTIME',
  dashboard_stage_prefix: 'CURRENT STAGE:',
  dashboard_stat_active: 'ACTIVE',
  dashboard_stat_connected: 'CONNECTED',
  dashboard_stat_judges: 'JUDGES',
  dashboard_stat_live_feed: 'LIVE FEED',
  dashboard_stat_mc: 'MC',
  dashboard_stat_offline: 'OFFLINE',
  dashboard_stat_online: 'ONLINE',
  dashboard_stat_spectators: 'SPECTATORS',
  dashboard_status_battles: 'BATTLES',
  dashboard_status_draft: 'DRAFT',
  dashboard_status_finished: 'FINISHED',
  dashboard_status_qualification: 'QUALIFICATION',
  dashboard_spectator_placeholder: 'Welcome, spectator.',
  dashboard_status_ranking: 'RANKING',
  go_home: "Go to home screen!",
  initial_setup: "Initial Setup",
  judge_badge_connected: 'CONNECTED',
  judge_badge_disconnected: 'DISCONNECTED',
  judge_badge_reconnecting: 'RECONNECTING',
  judge_criteria_difficulty: 'DIFFICULTY',
  judge_criteria_execution: 'EXECUTION',
  judge_criteria_musicality: 'MUSICALITY',
  judge_criteria_technique: 'TECHNIQUE',
  judge_dancer_a: 'DANCER A',
  judge_dancer_b: 'DANCER B',
  judge_heat_prefix: 'HEAT',
  judge_live_event: 'LIVE EVENT',
  judge_mode_label: 'JUDGE MODE',
  judge_numpad_label: 'JUDGE QUALIFICATION SCORING',
  judge_no_active_battle: 'No active battle — stand by.',
  judge_no_battle_body: 'Waiting for the host to start the next battle.',
  judge_numpad_scale: 'SYSTEM: 1-10 SCALE',
  judge_qualification_round: 'QUALIFICATION ROUND',
  judge_round_final: 'FINAL',
  judge_round_semifinal: 'SEMIFINAL',
  judge_round_top8: 'TOP 8',
  judge_submit_score: 'SUBMIT SCORE',
  judge_vote_a: 'VOTE A',
  judge_vote_b: 'VOTE B',
  judge_vote_confirm: 'CONFIRM VOTE',
  judge_vote_submitted: 'VOTE SUBMITTED',
  judge_voted_for_prefix: 'You voted for',
  judge_waiting_body: 'Voting will unlock once the final round ends.',
  judge_waiting_participant: 'Waiting for participant...',
  judge_waiting_title: 'WAITING FOR BATTLE TO FINISH',
  judging_connected_devices: "Connected Devices",
  judging_ip_address: "IP ADDRESS",
  judging_live_stream: "LIVE STREAM FEED",
  judging_port: "PORT",
  judging_refresh: "Refresh Connections",
  judging_scan_to_join: "SCAN TO JOIN",
  judging_subtitle: "Host Admin Control Connection",
  judging_total: "TOTAL:",
  judging_wifi_warning:
    "All devices must be connected to the same Wi-Fi network to establish a stable connection.",
  offline: "OFFLINE",
  online: "ONLINE",
  participants_add: 'ADD PARTICIPANT',
  participants_import_csv: 'IMPORT CSV',
  participants_search_placeholder: 'SEARCH DANCER, CREW, OR NUMBER...',
  participants_stat_checkin: 'CHECK-IN PROGRESS',
  participants_stat_present: 'CURRENTLY PRESENT',
  participants_stat_total: 'TOTAL REGISTERED',
  participants_status_absent: 'ABSENT',
  participants_status_present: 'PRESENT',
  participants_subtitle_prefix: 'Manage and track dancer registrations for',
  participants_title: 'BATTLEFLOW',
  ranking_cta_button: 'GENERATE BRACKET →',
  ranking_cta_label: 'NEXT PHASE: TOP 8 BRACKET / ROUND OF 16',
  ranking_description_prefix: 'Final standings for',
  ranking_description_suffix: '. The Top 8 competitors proceed to the main bracket.',
  ranking_header_name: 'NAME',
  ranking_header_number: '#',
  ranking_header_rank: 'RANK',
  ranking_live_label: 'LIVE QUALIFICATION',
  ranking_stat_avg_score: 'AVERAGE GROUP SCORE',
  ranking_stat_efficiency: 'JUDGING EFFICIENCY',
  ranking_stat_efficiency_value: '1.2 min avg / round',
  ranking_stat_final: 'FINAL',
  ranking_stat_status: 'STATUS',
  ranking_title: 'RANKINGS',
  result_archive: 'ARCHIVE RESULT',
  result_broadcast: 'CONFIRM & BROADCAST',
  result_complete: 'BATTLE COMPLETE',
  result_host_actions_title: 'HOST ACTIONS',
  result_judge_role_head: 'HEAD JUDGE',
  result_judge_role_standard: 'JUDGE',
  result_not_found: 'Battle not found.',
  result_representing_prefix: 'REPRESENTING:',
  result_verdict_title: 'JUDGE VERDICT',
  result_vote_prefix: 'VOTE',
  result_winner_badge: 'WINNER',
  result_winner_prefix: 'WINNER:',
  role_adjudicator: "ADJUDICATOR",
  role_mc: "MASTER OF CEREMONY",
  role_spectator: "SPECTATOR",
  role_spectators: "Spectators",
  role_selection_app_name: "BATTLEFLOW",
  role_selection_confirm: "CONFIRM ROLE",
  role_selection_docs: "TECHNICAL DOCS",
  role_selection_privacy: "PRIVACY POLICY",
  role_selection_pro_body:
    "BattleFlow runs on a low-latency local network architecture, ensuring zero lag for judges and instant score distribution even without stable internet.",
  role_selection_pro_link: "How local connection works →",
  role_selection_pro_title: "⚡ PRO PERFORMANCE",
  role_selection_status_online: "SYSTEMS ONLINE. LOCAL MODE",
  role_selection_subtitle:
    "Choose your interface based on your event duties. You can switch roles at any time from the Control Center.",
  role_selection_tagline: "DESIGNED FOR THE UNDERGROUND ELITE",
  role_selection_terms: "TERMS OF SERVICE",
  role_selection_title: "SELECT YOUR ROLE",
  screen_not_exist: "This screen doesn't exist.",
};

export type Resources = keyof typeof resources;
