export const resources = {
  app_loading: 'Loading...',
  app_storage_error: 'Storage error',
  battle_mock_votes: 'MOCK VOTES',
  battle_open_voting: 'OPEN VOTING',
  battle_start_battle: 'START BATTLE',
  bracket_battle_prefix: 'BATTLE #',
  bracket_feed_label: 'ON-AIR',
  bracket_feed_title: 'LIVE FEED',
  bracket_next_round_button: 'GENERATE NEXT ROUND →',
  bracket_next_round_title: 'NEXT ROUND',
  bracket_participants_prefix: 'PARTICIPANTS:',
  bracket_placeholder: 'Bracket will appear after qualification ends.',
  bracket_power_title: 'POWER RANKINGS',
  bracket_round_final: 'FINAL',
  bracket_round_semifinal: 'SEMIFINALS',
  bracket_round_top8: 'QUARTERFINALS',
  bracket_status_live: 'LIVE',
  bracket_status_pending: 'PENDING',
  bracket_status_voting: 'VOTING',
  bracket_status_winner: 'WINNER',
  bracket_title: 'PRO BRACKET',
  brackets_empty_add: '+ Add First Participant',
  brackets_empty_auto_seeding_body: 'Participants can be automatically seeded into brackets based on check-in time.',
  brackets_empty_auto_seeding_title: 'AUTO-SEEDING',
  brackets_empty_body: 'Start by adding dancers manually or importing a CSV file to begin organizing your bracket.',
  brackets_empty_checkin_body: 'Generate QR codes for dancers to register themselves via mobile devices.',
  brackets_empty_checkin_title: 'LIVE CHECK-IN',
  brackets_empty_import: 'Import CSV',
  brackets_empty_title: 'No participants yet',
  connection_lost_body: 'The synchronization with the tournament server was interrupted. Scores and battle progress are paused until the link is restored.',
  connection_lost_endpoint: 'LOCAL ENDPOINT',
  connection_lost_retry_attempt: 'RETRY ATTEMPT',
  connection_lost_retry_button: 'Retry Connection',
  connection_lost_settings_button: 'Network Settings',
  connection_lost_status: 'Offline status: Offline',
  connection_lost_title: 'Connection lost.\nReconnecting to local host...',
  content_not_found: "Content not found",
  dashboard_action_generate_top8: 'GENERATE TOP 8',
  dashboard_action_load_demo_event: 'LOAD DEMO EVENT',
  dashboard_action_mock_qualification: 'MOCK QUALIFICATION',
  dashboard_action_participants: 'MANAGE PARTICIPANTS',
  dashboard_action_show_qr: 'SHOW CONNECTION QR',
  dashboard_action_start_battles: 'START BATTLES',
  dashboard_action_start_qualification: 'START QUALIFICATION',
  dashboard_event_live: 'EVENT LIVE · HOST DASHBOARD',
  dashboard_hero_status: 'SYSTEM STANDBY',
  dashboard_hero_title: 'READY TO CLASH',
  dashboard_judge_hint: 'Use the JUDGING tab to score and vote.',
  dashboard_reset_role: 'RESET ROLE',
  create_event_title: 'NEW EVENT',
  create_event_name_label: 'EVENT NAME',
  create_event_category_label: 'CATEGORY / STYLE',
  create_event_format_label: 'BATTLE FORMAT',
  create_event_judges_label: 'NUMBER OF JUDGES',
  create_event_submit: 'CREATE EVENT',
  create_event_self_run_roles: 'SELF-RUN ROLES',
  dashboard_logs_title: 'SYSTEM LOGS',
  dashboard_mc_placeholder: 'MC view coming soon.',
  dashboard_server_health: 'HEALTH',
  dashboard_server_health_value: 'STABLE',
  dashboard_server_ip: 'IP ADDRESS',
  dashboard_server_local: 'LOCAL',
  dashboard_server_offline: 'OFFLINE',
  dashboard_server_online: 'ONLINE',
  dashboard_server_port: 'PORT',
  dashboard_server_title: 'SERVER STATUS',
  dashboard_server_uptime: 'UPTIME',
  dashboard_stage_prefix: 'CURRENT STAGE:',
  dashboard_stat_active: 'ACTIVE',
  dashboard_stat_connected: 'CONNECTED',
  dashboard_stat_judges: 'JUDGES',
  dashboard_stat_live_feed: 'LIVE FEED',
  dashboard_stat_mc: 'MC',
  dashboard_stat_offline: 'OFFLINE',
  dashboard_stat_online: 'ONLINE',
  dashboard_stat_spectators: 'SPECTATORS',
  dashboard_status_battles: 'BATTLES',
  dashboard_status_draft: 'DRAFT',
  dashboard_status_finished: 'FINISHED',
  dashboard_status_qualification: 'QUALIFICATION',
  dashboard_spectator_placeholder: 'Welcome, spectator.',
  dashboard_status_ranking: 'RANKING',
  discovery_create_event: 'CREATE EVENT',
  discovery_enter_manual: 'ENTER ADDRESS MANUALLY',
  discovery_host_section: 'HOST A TOURNAMENT',
  discovery_join_local: 'JOIN LOCAL EVENT',
  discovery_join_section: 'JOIN AS JUDGE, MC OR SPECTATOR',
  discovery_local_detected: 'LOCAL EVENT DETECTED',
  discovery_scan_qr: 'SCAN QR CODE',
  discovery_subtitle: 'YOUR DANCE TOURNAMENT PLATFORM',
  discovery_title: 'BATTLEFLOW',
  go_home: "Go to home screen!",
  initial_setup: "Initial Setup",
  judge_badge_connected: 'CONNECTED',
  judge_badge_disconnected: 'DISCONNECTED',
  judge_badge_reconnecting: 'RECONNECTING',
  judge_connect_address_label: 'SERVER ADDRESS',
  judge_connect_button: 'CONNECT',
  judge_connect_local_button: 'CONNECT TO LOCAL SERVER',
  judge_connect_local_detected: 'LOCAL SERVER DETECTED',
  judge_connect_name_label: 'YOUR NAME',
  judge_connect_name_placeholder: 'Your name',
  judge_connect_reconnecting_prefix: 'RECONNECTING',
  judge_connect_subtitle: 'Enter the host server address to join the event.',
  judge_connect_title: 'JOIN EVENT',
  judge_criteria_difficulty: 'DIFFICULTY',
  judge_criteria_execution: 'EXECUTION',
  judge_criteria_musicality: 'MUSICALITY',
  judge_criteria_technique: 'TECHNIQUE',
  judge_dancer_a: 'DANCER A',
  judge_dancer_b: 'DANCER B',
  judge_heat_prefix: 'HEAT',
  judge_live_event: 'LIVE EVENT',
  judge_mode_label: 'JUDGE MODE',
  judge_numpad_label: 'JUDGE QUALIFICATION SCORING',
  judge_no_active_battle: 'No active battle — stand by.',
  judge_no_battle_body: 'Waiting for the host to start the next battle.',
  judge_numpad_scale: 'SYSTEM: 1-10 SCALE',
  judge_qualification_round: 'QUALIFICATION ROUND',
  judge_round_final: 'FINAL',
  judge_round_semifinal: 'SEMIFINAL',
  judge_round_top8: 'TOP 8',
  judge_submit_score: 'SUBMIT SCORE',
  judge_vote_a: 'VOTE A',
  judge_vote_b: 'VOTE B',
  judge_vote_confirm: 'CONFIRM VOTE',
  judge_vote_submitted: 'VOTE SUBMITTED',
  judge_voted_for_prefix: 'You voted for',
  judge_waiting_body: 'Voting will unlock once the final round ends.',
  judge_waiting_host_open_voting: 'Waiting for Host to open voting',
  judge_waiting_participant: 'Waiting for participant...',
  judge_waiting_title: 'WAITING FOR BATTLE TO FINISH',
  judging_connected_devices: "Connected Devices",
  judging_ip_address: "IP ADDRESS",
  judging_live_stream: "LIVE STREAM FEED",
  judging_port: "PORT",
  judging_refresh: "Refresh Connections",
  judging_scan_to_join: "SCAN TO JOIN",
  judging_subtitle: "Host Admin Control Connection",
  judging_total: "TOTAL:",
  judging_wifi_warning:
    "All devices must be connected to the same Wi-Fi network to establish a stable connection.",
  live_tab_mc_only: 'This tab is for MC and Spectators.',
  host_qualification_finish: 'FINISH QUALIFICATION',
  host_qualification_judge_scores: 'JUDGE SCORES',
  host_qualification_next: 'NEXT PARTICIPANT',
  host_qualification_not_scored: 'NOT SCORED',
  host_qualification_progress: 'PARTICIPANT',
  host_qualification_title: 'QUALIFICATION CONTROL',
  mc_bpm: 'BPM',
  mc_live_event: 'LIVE EVENT',
  mc_next_up: 'NEXT UP',
  mc_now_dancing: 'NOW DANCING',
  mc_photo_placeholder: 'PHOTO',
  mc_prepare_deck: 'PREPARE DECK',
  mc_progress_label: 'PROGRESS',
  mc_participant_absent: 'Участник отсутствует',
  mc_participant_late: 'Опаздывает',
  mc_remaining: 'REMAINING',
  mc_stage_prefix: 'STAGE:',
  mc_stamina: 'STAMINA',
  mc_tech_art_placeholder: 'TECH: — | ART: —',
  mc_top8_title: 'TOP 8 RANKING',
  mc_view_archive: 'VIEW FULL ARCHIVE',
  offline: "OFFLINE",
  online: "ONLINE",
  participants_add: 'ADD PARTICIPANT',
  participants_import_csv: 'IMPORT CSV',
  participants_search_placeholder: 'SEARCH DANCER, CREW, OR NUMBER...',
  participants_stat_checkin: 'CHECK-IN PROGRESS',
  participants_stat_present: 'CURRENTLY PRESENT',
  participants_stat_total: 'TOTAL REGISTERED',
  participants_status_absent: 'ABSENT',
  participants_status_present: 'PRESENT',
  participants_subtitle_prefix: 'Manage and track dancer registrations for',
  participants_title: 'BATTLEFLOW',
  ranking_cta_button: 'GENERATE BRACKET →',
  ranking_cta_label: 'NEXT PHASE: TOP 8 BRACKET / ROUND OF 16',
  ranking_description_prefix: 'Final standings for',
  ranking_description_suffix: '. The Top 8 competitors proceed to the main bracket.',
  ranking_header_name: 'NAME',
  ranking_header_number: '#',
  ranking_header_rank: 'RANK',
  ranking_live_label: 'LIVE QUALIFICATION',
  ranking_stat_avg_score: 'AVERAGE GROUP SCORE',
  ranking_stat_efficiency: 'JUDGING EFFICIENCY',
  ranking_stat_efficiency_value: '1.2 min avg / round',
  ranking_stat_final: 'FINAL',
  ranking_stat_status: 'STATUS',
  ranking_title: 'RANKINGS',
  result_archive: 'ARCHIVE RESULT',
  result_broadcast: 'CONFIRM & BROADCAST',
  result_complete: 'BATTLE COMPLETE',
  result_host_actions_title: 'HOST ACTIONS',
  result_judge_role_head: 'HEAD JUDGE',
  result_judge_role_standard: 'JUDGE',
  result_not_found: 'Battle not found.',
  result_representing_prefix: 'REPRESENTING:',
  result_verdict_title: 'JUDGE VERDICT',
  result_vote_prefix: 'VOTE',
  result_winner_badge: 'WINNER',
  result_winner_prefix: 'WINNER:',
  role_adjudicator: "ADJUDICATOR",
  role_mc: "MASTER OF CEREMONY",
  role_spectator: "SPECTATOR",
  role_spectators: "Spectators",
  role_selection_app_name: "BATTLEFLOW",
  role_selection_confirm: "CONFIRM ROLE",
  role_selection_docs: "TECHNICAL DOCS",
  role_selection_privacy: "PRIVACY POLICY",
  role_selection_pro_body:
    "BattleFlow runs on a low-latency local network architecture, ensuring zero lag for judges and instant score distribution even without stable internet.",
  role_selection_pro_link: "How local connection works →",
  role_selection_pro_title: "⚡ PRO PERFORMANCE",
  role_selection_status_online: "SYSTEMS ONLINE. LOCAL MODE",
  role_selection_subtitle:
    "Choose your interface based on your event duties. You can switch roles at any time from the Control Center.",
  role_selection_tagline: "DESIGNED FOR THE UNDERGROUND ELITE",
  role_selection_terms: "TERMS OF SERVICE",
  role_selection_title: "SELECT YOUR ROLE",
  scan_qr_enter_manual: 'ENTER MANUALLY',
  scan_qr_label: 'SCAN BATTLEFLOW QR CODE',
  scan_qr_permission_button: 'Grant Permission',
  scan_qr_permission_title: 'CAMERA PERMISSION REQUIRED',
  screen_not_exist: "This screen doesn't exist.",
  spectator_audience: 'AUDIENCE',
  spectator_battle_mode: 'BATTLE MODE',
  spectator_bracket_title: 'TOURNAMENT BRACKET',
  spectator_intensity: 'INTENSITY',
  spectator_last_updated: 'LAST UPDATED',
  spectator_live_broadcast: 'LIVE BROADCAST',
  spectator_live_score: 'LIVE JUDGING SCORE',
  spectator_no_battle: 'No active battle — stand by.',
  spectator_origin_prefix: 'ORIGIN:',
  spectator_round_final: 'FINAL',
  spectator_round_quarter: 'QUARTER FINALS',
  spectator_round_semi: 'SEMI FINALS',
};

export type Resources = keyof typeof resources;
