export const resources = {
  app_loading: 'Loading...',
  app_storage_error: 'Storage error',
  battle_mock_votes: 'MOCK VOTES',
  battle_dashboard_judges: 'JUDGES',
  battle_dashboard_no_judges: 'No judges assigned to this battle yet.',
  battle_dashboard_participants: 'PARTICIPANTS',
  battle_dashboard_select: 'SELECT AS ACTIVE BATTLE',
  battle_dashboard_select_disabled: 'Active battle can be changed only before qualification starts.',
  battle_dashboard_title: 'BATTLE DASHBOARD',
  battle_open_voting: 'OPEN VOTING',
  battle_start_battle: 'START BATTLE',
  bracket_battle_prefix: 'BATTLE #',
  bracket_feed_label: 'ON-AIR',
  bracket_feed_title: 'LIVE FEED',
  bracket_next_round_button: 'GENERATE NEXT ROUND →',
  bracket_next_round_title: 'NEXT ROUND',
  bracket_participants_prefix: 'PARTICIPANTS:',
  bracket_placeholder: 'Bracket will appear after qualification ends.',
  bracket_power_title: 'POWER RANKINGS',
  bracket_round_final: 'FINAL',
  bracket_round_custom: 'BRACKET',
  bracket_round_semifinal: 'SEMIFINALS',
  bracket_round_top16: 'TOP 16',
  bracket_round_top32: 'TOP 32',
  bracket_round_top8: 'QUARTERFINALS',
  bracket_status_live: 'LIVE',
  bracket_status_pending: 'PENDING',
  bracket_status_voting: 'VOTING',
  bracket_status_winner: 'WINNER',
  bracket_title: 'PRO BRACKET',
  brackets_empty_add: '+ Add First Participant',
  brackets_empty_auto_seeding_body: 'Participants can be automatically seeded into brackets based on check-in time.',
  brackets_empty_auto_seeding_title: 'AUTO-SEEDING',
  brackets_empty_body: 'Start by adding dancers manually or importing a CSV file to begin organizing your bracket.',
  brackets_empty_checkin_body: 'Generate QR codes for dancers to register themselves via mobile devices.',
  brackets_empty_checkin_title: 'LIVE CHECK-IN',
  brackets_empty_import: 'Import CSV',
  brackets_empty_title: 'No participants yet',
  connection_lost_body: 'The synchronization with the tournament server was interrupted. Scores and battle progress are paused until the link is restored.',
  connection_lost_endpoint: 'LOCAL ENDPOINT',
  connection_lost_retry_attempt: 'RETRY ATTEMPT',
  connection_lost_retry_button: 'Retry Connection',
  connection_lost_settings_button: 'Network Settings',
  connection_lost_status: 'Offline status: Offline',
  connection_lost_title: 'Connection lost.\nReconnecting to local host...',
  content_not_found: "Content not found",
  dashboard_action_generate_bracket: 'GENERATE BRACKET',
  dashboard_action_create_battle: 'CREATE BATTLE',
  dashboard_action_load_demo_battle: 'LOAD DEMO BATTLE',
  dashboard_action_mock_qualification: 'MOCK QUALIFICATION',
  dashboard_action_participants: 'MANAGE PARTICIPANTS',
  dashboard_action_show_qr: 'SHOW CONNECTION QR',
  dashboard_action_start_battles: 'START BATTLES',
  dashboard_action_start_qualification: 'START QUALIFICATION',
  dashboard_bracket_cta_body: 'Select the qualified dancers who should enter the bracket.',
  dashboard_bracket_cta_button: 'SELECT BRACKET PARTICIPANTS',
  dashboard_bracket_cta_title: 'Qualification finished',
  dashboard_connected_users_empty: 'No connected users yet.',
  dashboard_connected_users_title: 'CONNECTED USERS',
  dashboard_list_assign_judge: 'ASSIGN JUDGE',
  dashboard_list_assign_mc: 'ASSIGN MC',
  dashboard_list_assign_spectator: 'ASSIGN SPECTATOR',
  dashboard_list_close: 'Close list',
  dashboard_list_connected_title: 'CONNECTED USERS',
  dashboard_list_empty: 'Nothing to show yet.',
  dashboard_list_judges_title: 'JUDGES',
  dashboard_list_mc_title: 'MC',
  dashboard_list_participants_title: 'PARTICIPANTS',
  dashboard_list_spectators_title: 'SPECTATORS',
  dashboard_event_live: 'EVENT LIVE · HOST DASHBOARD',
  dashboard_hero_status: 'SYSTEM STANDBY',
  dashboard_hero_title: 'READY TO CLASH',
  dashboard_judge_hint: 'Use the JUDGING tab to score and vote.',
  dashboard_reset_role: 'RESET ROLE',
  create_event_title: 'NEW EVENT',
  create_event_name_label: 'EVENT NAME',
  create_event_name_placeholder: 'Urban Clash 2026',
  create_event_continue: 'CONTINUE TO BATTLE SETUP',
  create_event_finish: 'FINISH',
  create_event_category_label: 'CATEGORY / STYLE',
  create_event_format_label: 'BATTLE FORMAT',
  create_event_judges_label: 'NUMBER OF JUDGES',
  create_event_submit: 'CREATE EVENT',
  create_event_self_run_roles: 'SELF-RUN ROLES',
  configure_battle_title: 'BATTLE SETUP',
  configure_battle_subtitle: 'The bracket will be built from qualification ranking.',
  configure_battle_category_placeholder: 'Hip-Hop 1x1',
  configure_battle_duration_label: 'QUALIFICATION DURATION (SECONDS)',
  configure_battle_advance_mode_label: 'QUALIFICATION ADVANCE MODE',
  configure_battle_advance_mode_description: 'Manual keeps the current dancer active until Host or MC moves to the next one. Automatic moves to the next dancer when the timer ends.',
  configure_battle_advance_manual: 'MANUAL',
  configure_battle_advance_automatic: 'AUTOMATIC',
  configure_battle_role_mc: 'MC / PRESENTER',
  configure_battle_role_judge: 'JUDGE',
  configure_battle_host_judge_name: 'Host Judge',
  configure_battle_save: 'SAVE',
  configure_battle_format_top8: 'TOP 8',
  configure_battle_format_top16: 'TOP 16',
  configure_battle_format_top32: 'TOP 32',
  dashboard_logs_title: 'SYSTEM LOGS',
  dashboard_menu_close: 'Close host menu',
  dashboard_menu_open: 'Open host menu',
  dashboard_menu_title: 'HOST ACTIONS',
  dashboard_view_host: 'HOST CONTROL',
  dashboard_view_judge: 'JUDGE VIEW',
  dashboard_view_mc: 'MC VIEW',
  dashboard_view_spectator: 'SPECTATOR VIEW',
  dashboard_mc_placeholder: 'MC view coming soon.',
  dashboard_server_health: 'HEALTH',
  dashboard_server_health_value: 'STABLE',
  dashboard_server_ip: 'IP ADDRESS',
  dashboard_server_local: 'LOCAL',
  dashboard_server_offline: 'OFFLINE',
  dashboard_server_online: 'ONLINE',
  dashboard_server_port: 'PORT',
  dashboard_server_retry: 'RETRY SERVER',
  dashboard_server_title: 'SERVER STATUS',
  dashboard_server_uptime: 'UPTIME',
  dashboard_stage_prefix: 'CURRENT STAGE:',
  dashboard_stat_active: 'ACTIVE',
  dashboard_stat_connected: 'CONNECTED',
  dashboard_stat_judges: 'JUDGES',
  dashboard_stat_live_feed: 'LIVE FEED',
  dashboard_stat_mc: 'MC',
  dashboard_stat_offline: 'OFFLINE',
  dashboard_stat_online: 'ONLINE',
  dashboard_stat_spectators: 'SPECTATORS',
  dashboard_status_battles: 'BATTLES',
  dashboard_status_draft: 'DRAFT',
  dashboard_status_finished: 'FINISHED',
  dashboard_status_qualification: 'QUALIFICATION',
  dashboard_spectator_placeholder: 'Welcome, spectator.',
  dashboard_status_ranking: 'RANKING',
  discovery_connect_own_local: 'GO TO LOCAL EVENT',
  discovery_create_event: 'CREATE EVENT',
  discovery_delete_local_cancel: 'CANCEL',
  discovery_delete_local_confirm: 'DELETE',
  discovery_delete_local_message: 'This will close the local event channel and remove the saved event from this device.',
  discovery_delete_local_title: 'Delete local event?',
  discovery_enter_manual: 'ENTER ADDRESS MANUALLY',
  discovery_host_section: 'HOST A TOURNAMENT',
  discovery_join_local: 'JOIN LOCAL EVENT',
  discovery_join_section: 'JOIN AS JUDGE, MC OR SPECTATOR',
  discovery_local_detected: 'LOCAL EVENT DETECTED',
  discovery_local_reconnect: 'LOCAL EVENT READY TO RECONNECT',
  discovery_role_host: 'HOST',
  discovery_role_judge: 'JUDGE',
  discovery_role_mc: 'MC',
  discovery_role_spectator: 'SPECTATOR',
  discovery_scan_qr: 'SCAN QR CODE',
  discovery_subtitle: 'YOUR DANCE TOURNAMENT PLATFORM',
  discovery_title: 'BATTLEFLOW',
  go_home: "Go to home screen!",
  initial_setup: "Initial Setup",
  judge_badge_connected: 'CONNECTED',
  judge_badge_disconnected: 'DISCONNECTED',
  judge_badge_reconnecting: 'RECONNECTING',
  judge_connect_address_label: 'SERVER ADDRESS',
  judge_connect_button: 'CONNECT',
  judge_connect_local_button: 'CONNECT TO LOCAL SERVER',
  judge_connect_local_detected: 'LOCAL SERVER DETECTED',
  judge_connect_name_label: 'YOUR NAME',
  judge_connect_name_placeholder: 'Your name',
  judge_connect_reconnecting_prefix: 'RECONNECTING',
  judge_connect_subtitle: 'Enter the host server address to join the event.',
  judge_connect_title: 'JOIN EVENT',
  judge_criteria_difficulty: 'DIFFICULTY',
  judge_criteria_execution: 'EXECUTION',
  judge_criteria_musicality: 'MUSICALITY',
  judge_criteria_technique: 'TECHNIQUE',
  judge_dancer_a: 'DANCER A',
  judge_dancer_b: 'DANCER B',
  judge_dancer_label: 'DANCER',
  judge_heat_prefix: 'HEAT',
  judge_live_event: 'LIVE EVENT',
  judge_mode_label: 'JUDGE MODE',
  judge_numpad_label: 'JUDGE QUALIFICATION SCORING',
  judge_no_active_battle: 'No active battle — stand by.',
  judge_no_battle_body: 'Waiting for the host to start the next battle.',
  judge_numpad_scale: 'SYSTEM: 1-10 SCALE',
  judge_current_participant: 'CURRENT',
  judge_list_view: 'LIST',
  judge_next_participant: 'NEXT',
  judge_previous_participant: 'BACK',
  judge_qualification_round: 'QUALIFICATION ROUND',
  judge_round_final: 'FINAL',
  judge_round_semifinal: 'SEMIFINAL',
  judge_round_top8: 'TOP 8',
  judge_score_submitted: 'SCORE SUBMITTED',
  judge_score_view: 'SCORE',
  judge_submit_score: 'SUBMIT SCORE',
  judge_vote_a: 'VOTE A',
  judge_vote_b: 'VOTE B',
  judge_vote_confirm: 'CONFIRM VOTE',
  judge_vote_prefix: 'VOTE',
  judge_vote_submitted: 'VOTE SUBMITTED',
  judge_voted_for_prefix: 'You voted for',
  judge_waiting_body: 'Voting will unlock once the final round ends.',
  judge_waiting_host_open_voting: 'Waiting for Host to open voting',
  judge_waiting_participant: 'Waiting for participant...',
  judge_waiting_title: 'WAITING FOR BATTLE TO FINISH',
  judging_connected_devices: "Connected Devices",
  judging_ip_address: "IP ADDRESS",
  judging_live_stream: "LIVE STREAM FEED",
  judging_port: "PORT",
  judging_refresh: "Refresh Connections",
  judging_scan_to_join: "SCAN TO JOIN",
  judging_subtitle: "Host Admin Control Connection",
  judging_total: "TOTAL:",
  judging_wifi_warning:
    "All devices must be connected to the same Wi-Fi network to establish a stable connection.",
  live_tab_mc_only: 'This tab is for MC and Spectators.',
  host_qualification_finish: 'FINISH QUALIFICATION',
  host_qualification_judge_scores: 'JUDGE SCORES',
  host_qualification_next: 'NEXT PARTICIPANT',
  host_qualification_not_scored: 'NOT SCORED',
  host_qualification_progress: 'PARTICIPANT',
  host_qualification_title: 'QUALIFICATION CONTROL',
  host_battles_active: 'ACTIVE',
  host_battles_create: 'CREATE BATTLE',
  host_battles_empty_body: 'Create categories for this event, then select the one you want to run.',
  host_battles_empty_title: 'No battles yet',
  host_battles_format_pending: 'BRACKET AFTER QUALIFICATION',
  host_battles_judges_suffix: 'judges',
  host_battles_overline: 'HOST EVENT',
  host_battles_select_disabled: 'Battle selection is available before qualification starts.',
  host_battles_title: 'BATTLES',
  host_tabs_battles: 'BATTLES',
  host_tabs_dashboard: 'DASHBOARD',
  mc_bpm: 'BPM',
  mc_live_event: 'LIVE EVENT',
  mc_next_up: 'NEXT UP',
  mc_now_dancing: 'NOW DANCING',
  mc_photo_placeholder: 'PHOTO',
  mc_prepare_deck: 'PREPARE DECK',
  mc_progress_label: 'PROGRESS',
  mc_remaining: 'REMAINING',
  mc_stage_prefix: 'STAGE:',
  mc_stamina: 'STAMINA',
  mc_tech_art_placeholder: 'TECH: — | ART: —',
  mc_top8_title: 'TOP 8 RANKING',
  mc_view_archive: 'VIEW FULL ARCHIVE',
  offline: "OFFLINE",
  online: "ONLINE",
  participants_add: 'ADD PARTICIPANT',
  participants_add_required_error: 'Name and number are required.',
  participants_add_short: 'ADD',
  participants_cancel: 'CANCEL',
  participants_city_placeholder: 'City',
  participants_crew_placeholder: 'Crew',
  participants_empty_search: 'No participants found.',
  participants_import_csv: 'IMPORT CSV',
  participants_import_empty_error: 'No valid participants were found in the selected file.',
  participants_import_error_title: 'Import failed',
  participants_import_excel: 'IMPORT EXCEL',
  participants_import_failed_error: 'Could not import participants.',
  participants_import_success_suffix: 'participants imported.',
  participants_import_success_title: 'Import complete',
  participants_importing: 'IMPORTING...',
  participants_name_placeholder: 'Name *',
  participants_number_placeholder: 'Number *',
  participants_search_placeholder: 'SEARCH DANCER, CREW, OR NUMBER...',
  participants_stat_checkin: 'CHECK-IN PROGRESS',
  participants_stat_present: 'CURRENTLY PRESENT',
  participants_stat_total: 'TOTAL REGISTERED',
  participants_status_absent: 'ABSENT',
  participants_status_present: 'PRESENT',
  participants_subtitle_prefix: 'Manage and track dancer registrations for',
  participants_title: 'BATTLEFLOW',
  ranking_cta_button: 'GENERATE BRACKET →',
  ranking_cta_label: 'NEXT PHASE: BATTLE BRACKET',
  ranking_bracket_size_label: 'BRACKET SIZE',
  ranking_select: 'ADD',
  ranking_selected: 'IN',
  ranking_selected_count_prefix: 'SELECTED:',
  ranking_description_prefix: 'Final standings for',
  ranking_description_suffix: '. Top-ranked competitors proceed to the selected bracket.',
  ranking_header_name: 'NAME',
  ranking_header_number: '#',
  ranking_header_rank: 'RANK',
  ranking_live_label: 'LIVE QUALIFICATION',
  ranking_stat_avg_score: 'AVERAGE GROUP SCORE',
  ranking_stat_efficiency: 'JUDGING EFFICIENCY',
  ranking_stat_efficiency_value: '1.2 min avg / round',
  ranking_stat_final: 'FINAL',
  ranking_stat_status: 'STATUS',
  ranking_title: 'RANKINGS',
  result_archive: 'ARCHIVE RESULT',
  result_broadcast: 'CONFIRM & BROADCAST',
  result_complete: 'BATTLE COMPLETE',
  result_host_actions_title: 'HOST ACTIONS',
  result_judge_role_head: 'HEAD JUDGE',
  result_judge_role_standard: 'JUDGE',
  result_not_found: 'Battle not found.',
  result_representing_prefix: 'REPRESENTING:',
  result_verdict_title: 'JUDGE VERDICT',
  result_vote_prefix: 'VOTE',
  result_winner_badge: 'WINNER',
  result_winner_prefix: 'WINNER:',
  role_adjudicator: "ADJUDICATOR",
  role_mc: "MASTER OF CEREMONY",
  role_spectator: "SPECTATOR",
  role_spectators: "Spectators",
  role_selection_app_name: "BATTLEFLOW",
  role_selection_confirm: "CONFIRM ROLE",
  role_selection_docs: "TECHNICAL DOCS",
  role_selection_privacy: "PRIVACY POLICY",
  role_selection_pro_body:
    "BattleFlow runs on a low-latency local network architecture, ensuring zero lag for judges and instant score distribution even without stable internet.",
  role_selection_pro_link: "How local connection works →",
  role_selection_pro_title: "⚡ PRO PERFORMANCE",
  role_selection_status_online: "SYSTEMS ONLINE. LOCAL MODE",
  role_selection_subtitle:
    "Choose your interface based on your event duties. You can switch roles at any time from the Control Center.",
  role_selection_tagline: "DESIGNED FOR THE UNDERGROUND ELITE",
  role_selection_terms: "TERMS OF SERVICE",
  role_selection_title: "SELECT YOUR ROLE",
  scan_qr_enter_manual: 'ENTER MANUALLY',
  scan_qr_label: 'SCAN BATTLEFLOW QR CODE',
  scan_qr_permission_button: 'Grant Permission',
  scan_qr_permission_title: 'CAMERA PERMISSION REQUIRED',
  screen_not_exist: "This screen doesn't exist.",
  spectator_audience: 'AUDIENCE',
  spectator_battle_mode: 'BATTLE MODE',
  spectator_bracket_title: 'TOURNAMENT BRACKET',
  spectator_intensity: 'INTENSITY',
  spectator_last_updated: 'LAST UPDATED',
  spectator_last_battle_result: 'LAST BATTLE RESULT',
  spectator_live_broadcast: 'LIVE BROADCAST',
  spectator_live_score: 'LIVE JUDGING SCORE',
  spectator_no_battle: 'No active battle — stand by.',
  spectator_origin_prefix: 'ORIGIN:',
  spectator_champion_prefix: 'CHAMPION:',
  spectator_final_results: 'FINAL RESULTS',
  spectator_result_score: 'BATTLE RESULT',
  spectator_results_title: 'BATTLE WINNERS',
  spectator_round_final: 'FINAL',
  spectator_round_quarter: 'QUARTER FINALS',
  spectator_round_semi: 'SEMI FINALS',
  spectator_winner_label: 'WINNER',
  spectator_winner_prefix: 'WINNER:',
  top_menu_close: 'Close app menu',
  top_menu_exit: 'EXIT',
  top_menu_go_home: 'GO TO MAIN SCREEN',
  top_menu_host_actions: 'HOST ACTIONS',
  top_menu_open: 'Open app menu',
  top_menu_screen_brackets: 'BRACKETS',
  top_menu_screens: 'SCREENS',
  top_menu_title: 'MENU',
};

export type Resources = keyof typeof resources;
